services:
  - name: llama2-med-bot
    type: web
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python ingest.py  # Ensure embeddings are created
    startCommand: chainlit run model.py --port 10000
    envVars:
      - key: DB_FAISS_PATH
        value: "vectorstore/db_faiss"
